{
 "title": "LEXEMO Latenzen",
 "tags": [
  "lexemo",
  "latenz"
 ],
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "60s",
 "panels": [
  {
   "title": "Lexemo-Antragsrücknahme",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "playwright_latency{test=\"Latenztest-Lexemo-Antragsrücknahme\",browser=~\".*\"}",
     "legendFormat": "{{browser}}"
    }
   ]
  },
  {
   "title": "Endpunkt HighQ",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 9 },
   "targets": [
    {
     "expr": "playwright_latency{test=\"Endpunkt HighQ\",browser=~\".*\"}",
     "legendFormat": "{{browser}}"
    }
   ]
  },
  {
   "title": "Endpunkt Lexemo",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 18 },
   "targets": [
    {
     "expr": "playwright_latency{test=\"Endpunkt Lexemo\",browser=~\".*\"}",
     "legendFormat": "{{browser}}"
    }
   ]
  }
 ]
}